language: go
go: 
  - 1.2
  
before_script:
  - go get gopkg.in/check.v1

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls -repotoken HGtRzYCVFoeamth9KhOF1KuiiFiwVSflt
